[build]
  command = "bun install && bun run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  node_version = "18"
  external_node_modules = ["hono"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
