services:
  - type: web
    name: api-rubber-hono
    runtime: bun
    buildCommand: bun install && bun build src/server.ts --outdir dist
    startCommand: bun dist/server.js
    envVars:
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
