services:
  - type: web
    name: api-rubber
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_VERSION
        value: 18
