services:
  - type: web
    name: api-rubber-hono
    runtime: bun
    buildCommand: bun install && bun run build
    startCommand: bun run start
    envVars:
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
